---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gesuntight.
--- DateTime: 25.05.2022 18:31
---
module(..., package.seeall)
_G.main_env = getfenv(1);


scripting = require "lua_scripts.EpisodicScripting";
utility = require "script._lib.DeI_utility_functions";
CA = require "script.lib.lib_campaign_manager";

-- Log

isLogAllowed = true;

-- Log function

function Log(text, isTitle, isNew)
    if not isLogAllowed then return end

    local logfile;
    text = tostring(text);
    if isNew then
        logfile = io.open("Seleucid_Borders.txt","w");
        local curr_date = os.date("%A, %m %B %Y");
        local text = tostring("- Seleucid Borders\n".."- "..curr_date);
        logfile:write(text.."\n\n");
    else
        logfile = io.open("Seleucid_Borders.txt","a");
        if not logfile then logfile = io.open("Seleucid_Borders.txt","w") end
    end

    if isTitle then
        local title_text = "*************************************************************************\n";
        text = "\n"..title_text..text.."\n"..title_text;
    end

    logfile:write(text.."\n");
    logfile:close();
end


local function Seleucid_Borders(context)

    local _EQU_Player_Faction_Name = context:faction():name()

    if conditions.FactionIsHuman(context)
            and context:faction():name() == "rom_seleucid"
            and context:faction():is_human() == true
            and conditions.TurnNumber(context) == 1
    then

        scripting.game_interface:transfer_region_to_faction("emp_persis_susa", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_persis_persepolis", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_persis_gor", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_carmania_bam", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_carmania_harmozia", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_media_magna_arsakia", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_parthia_zadrakata", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_parthia_hekatompylos", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_parthia_susia", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_gedrosia_phrada", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_aria_artacoana", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_aria_merv", "rom_seleucid")

        scripting.game_interface:transfer_region_to_faction("emp_galatia_et_cappadocia_iconium", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_asia_pessinus", "rom_seleucid")
        scripting.game_interface:transfer_region_to_faction("emp_asia_ephesus", "rom_seleucid")

    end
end

--[[
local function Kill_Satraps(context)
    local satrapies =
    {
        "rom_drangiana",
        "rom_parthava",
        "rom_persia",
        "rom_sardes",
        "rom_aria",
        "rom_sagartia",
    }

    local model = game_interface:model()
    self.local_faction = get_local_faction_name(model);
    Log("local_faction:" + local_faction )
    char_x, char_y = char_display_pos(get_faction_leader(scripting, local_faction));
    Log("char_x: ("..char_x..")")
    Log("char_y: ("..char_y..")")

    for i = 1, #satrapies do
        local faction = satrapies[i]
        Log("faction:("..faction..")")
        if context:character():faction():name() == faction
                and context:character():logical_position_x() == char_x
                and context:character():logical_position_y() == char_y
        then
            --faction = "faction:"..tostring(context:character():faction():name())
            forename = context:character():get_forename()
            forename = "forename:"..string.gsub(forename,"names_name_","")
            target = faction..","..forename
            scripting.game_interface:kill_character(target, true, true)
        end

    end

end
]]--
scripting.AddEventCallBack("FactionTurnStart", Seleucid_Borders)
--scripting.AddEventCallBack("CharacterTurnStart", Kill_Satraps)



